id: AE45358EB
base_file: fF085.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:05:37.274436
  last_modified_at: 2022-06-05 20:05:37.274443
